version: '3.3'

services:

  backend:
    image: afc-senti/backend
    container_name: afc-senti-backend
    build:
      context: backend/
      dockerfile: Dockerfile
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - './backend/:/app'
    working_dir: /app
    restart: always
    ports:
      - "8000:8000"

  frontend:
    image: afc-senti/frontend
    container_name: afc-senti-frontend
    build:
      context: frontend/
      dockerfile: Dockerfile
    working_dir: /app
    tty: true
    volumes:
      # note: this mount will override node_modules in the container, so run yarn install again after build
      - './frontend/:/app'
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true